on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ESLint-Evaluator:
    runs-on: self-hosted
    name: ESLint
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch ESLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/eslint-linter-action
          ref: v3
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/eslint-evaluator

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run ESLint evaluator
        uses: ./.github/actions/eslint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          
  Evaluator:
    runs-on: self-hosted
    name: Evaluator
    needs: [ESLint-Evaluator]
    services:
      mongodb:
        image: mongo:latest@sha256:ff4050d808f943c0835c0aa24cce07afd86193253713020ca399a2b6c7840a03
        ports:
          - "27017:27017"
        options: -v ${{ github.workspace }}:/github/workspace
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch MongoDB Query evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/mongodb-query-evaluator-action
          ref: v5.1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/mongodb-query-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v5
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run MongoDB Query evaluator
        uses: ./.github/actions/mongodb-query-evaluator  
        id: mongodb_evaluator
        env:
          DBNAME: 'commerce'
        with:
          db_restore_dir: 'assets'
          challenges_dir: 'challenges'
          pr_author_username: ${{ github.event.pull_request.user.login }}

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.mongodb_evaluator.outputs.result }}
          environment: production
